index:
    path: /
    defaults: { _controller: 'App\Controller\PersonController::index' }

newPerson:
    path: /newPerson
    defaults: { _controller: 'App\Controller\PersonController::newPerson' }

newMaterial:
    path: /newMaterial
    defaults: { _controller: 'App\Controller\MaterialController::newMaterial' }

newInventory:
    path: /newInventory
    defaults: { _controller: 'App\Controller\InventoryController::newInventory' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
