index:
    path: /
    defaults: { _controller: 'App\Controller\PersonController::index' }

newPerson:
    path: /new
    defaults: { _controller: 'App\Controller\PersonController::newPerson' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
